name: "Ping Render"

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        uses: sisodiya2421/pinger@master
        env:
          URL: ${{secrets.URL}}
          METHOD: "GET"
